In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_o = pd.read_excel('adriel_qualitativas.xlsx')

df = df_o[:]

df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace('\n', '', regex=True)

print(len(df))

print(df.columns.tolist())

95

In [5]:
print(df['Você tem (ou teve) alguma experiência de trabalho relacionada à segurança de software no processo de desenvolvimento de software?'].unique())


df = df[~(df['Você tem (ou teve) alguma experiência de trabalho relacionada à segurança de software no processo de desenvolvimento de software?'] == 'Nunca tive experiência direta e nem indireta com segurança no processo de desenvolvimento de software')]

print(df['Você tem (ou teve) alguma experiência de trabalho relacionada à segurança de software no processo de desenvolvimento de software?'].unique())
print(df.shape)

['Nunca tive experiência direta e nem indireta com segurança no processo de desenvolvimento de software'
 'Meu grupo/equipe de desenvolvimento trabalha (ou trabalhou) com segurança, mas não estou diretamente envolvido em nenhuma tarefa.'
 'Eu já trabalhei (ou trabalho) com segurança no processo de desenvolvimento de software.']
['Meu grupo/equipe de desenvolvimento trabalha (ou trabalhou) com segurança, mas não estou diretamente envolvido em nenhuma tarefa.'
 'Eu já trabalhei (ou trabalho) com segurança no processo de desenvolvimento de software.']
(83, 103)

In [6]:
df.isna().sum()

ID                                                                                                                                                                                                                                                                                                                                                                                                                                                              0
Carimbo de data/hora                                                                                                                                                                                                                                                                                                                                                                                                                                            0
Após ter recebido esclarecimentos sobre a natureza da pesquisa, seus objetivos e métodos, eu declaro que sou maior de 18 anos e aceito participar por meio do formulário de participação, conforme as disposições da Lei Geral de Proteção de Dados (Lei nº 13.709/2018).Em caso de resposta negativa, o formulário será encerrado, garantindo assim o respeito à autonomia e privacidade dos participantes, conforme estabelecido pela legislação vigente.     0
Qual é a sua idade?                                                                                                                                                                                                                                                                                                                                                                                                                                             0
Em qual estado do Brasil você mora atualmente?                                                                                                                                                                                                                                                                                                                                                                                                                  0
                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Quais são as razões pelas quais você opta por não utilizar ferramentas automatizadas de segurança de software? Por favor, descreva brevemente sobre.                                                                                                                                                                                                                                                                                                           69
Você considera utilizar ferramentas automatizadas de segurança de software em seus projetos no futuro?                                                                                                                                                                                                                                                                                                                                                         69
Se você respondeu "Sim" ou "Talvez" à pergunta anterior, por favor, indique quais ferramentas utilizaria. Marque "Nenhuma" se respondeu "Não".                                                                                                                                                                                                                                                                                                                 69
Caso você queira receber os resultados desse estudo e participar de uma futura entrevista sobre Práticas de Segurança de Software, por favor, informe seu Email..1                                                                                                                                                                                                                                                                                             81
Marque a imagem em que aparece um filhote de cachorro:                                                                                                                                                                                                                                                                                                                                                                                                          0
Length: 103, dtype: int64

In [7]:
df.shape

(83, 103)

Analises

In [8]:
categorias = {
    "3rd Party Vulnerability Scanning": [
        "Dependabot", "PHP Security Checker", "Snyk", "Clair", "Blackduck",
        "Retire.JS", "SRC:CLR", "Anchore", "Node Security Platform", "Trivy",
        "Sonatype", "Whitesource"
    ],
    "Static Application Security Testing": [  # SAST
        "CodeQL", "CheckStyle", "Coverity", "SonarQube", "Bandit", "PHPStan",
        "LGTM", "Brakeman", "ESLint Security", "Dart Analyzer", "DevSkim"
    ],
    "Dynamic Application Security Testing": [  # DAST
        "Qark", "Checkmarx", "CFN NAG"
    ],
    "Secure Configuration/Hardening": [
        "Chef", "Ansible", "Terraform", "Puppet", "Phan", "Seccomp",
        "CloudCustodian", "Turbot"
    ],
    "Compliance/Hardening Checks": [
        "Bane", "Ansible-Lint", "Blackbox", "Puppet-Lint", "InSpec",
        "Kube Audit", "Foodcritic", "Cookstyle", "conftest"
    ],
    "Secrets Management": [
        "Pinterest Knox", "GitLeaks", "CyberArk Conjur",
        "ThoughtWorks Talisman", "Berglas", "Docker Secrets", "Trufflehog"
    ]
}

In [9]:
cols_ferramentas = [
    col for col in df.columns
    if "categorias de ferramentas" in str(col).lower()
]

print(f"\n{len(cols_ferramentas)} colunas encontradas para a pergunta das ferramentas:")
for c in cols_ferramentas:
    print("-", c)

df_ferramentas = df[cols_ferramentas].copy()

6 colunas encontradas para a pergunta das ferramentas:
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [3rd Party Vulnerability Scanning Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Static Application Security Testing Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Secure Configuration/Hardening Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Compliance/Hardening Checks Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Secrets Management Tools]

In [10]:
df_ferramentas = df_ferramentas.applymap(
    lambda x: x.strip() if isinstance(x, str) else x
)

C:\Users\adrie\AppData\Local\Temp\ipykernel_2624\1321544343.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_ferramentas = df_ferramentas.applymap(

In [11]:
df_ferramentas.insert(0, "Respondente", range(1, len(df_ferramentas) + 1))

In [12]:
escala_likert = [
    "Diariamente",
    "Semanalmente",
    "Mensalmente",
    "Anualmente",
    "Não Aplicável",
]

In [13]:
resultado = {}

for categoria in df_ferramentas.columns[1:]:  # ignora a coluna "Respondente"
    resultado[categoria] = {}
    for opcao in escala_likert:
        # Seleciona todas as linhas onde o respondente marcou essa opção
        participantes = df_ferramentas[df_ferramentas[categoria] == opcao][["Respondente", categoria]]

        # Armazena as respostas individuais
        resultado[categoria][opcao] = participantes

In [14]:
exemplo_categoria = list(resultado.keys())[2]
print(f"\nExemplo — Categoria: {exemplo_categoria}")
for opcao, respostas in resultado[exemplo_categoria].items():
    print(f"\nOpção: {opcao}")
    print(respostas)

Exemplo — Categoria: Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]

Opção: Diariamente
    Respondente  \
4             4
5             5
24           21
28           24
32           28
33           29
34           30
37           33
54           47
63           56
75           66
77           68
80           71
84           75
91           81
92           82

   Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
4                                         Diariamente
5                                         Diariamente
24                                        Diariamente
28                                        Diariamente
32                                        Diariamente
33                                        Diariamente
34                                        Diariamente
37                                        Diariamente
54                                        Diariamente
63                                        Diariamente
75                                        Diariamente
77                                        Diariamente
80                                        Diariamente
84                                        Diariamente
91                                        Diariamente
92                                        Diariamente

Opção: Semanalmente
    Respondente  \
16           13
17           14
18           15
19           16
23           20
26           22
31           27
45           40
46           41
49           44
52           45
58           51
61           54
62           55
64           57
67           59
74           65
76           67

   Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
16                                       Semanalmente
17                                       Semanalmente
18                                       Semanalmente
19                                       Semanalmente
23                                       Semanalmente
26                                       Semanalmente
31                                       Semanalmente
45                                       Semanalmente
46                                       Semanalmente
49                                       Semanalmente
52                                       Semanalmente
58                                       Semanalmente
61                                       Semanalmente
62                                       Semanalmente
64                                       Semanalmente
67                                       Semanalmente
74                                       Semanalmente
76                                       Semanalmente

Opção: Mensalmente
    Respondente  \
6             6
12           11
27           23
42           37
47           42
48           43
66           58
72           64
78           69
79           70
81           72
82           73
90           80

   Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
6                                         Mensalmente
12                                        Mensalmente
27                                        Mensalmente
42                                        Mensalmente
47                                        Mensalmente
48                                        Mensalmente
66                                        Mensalmente
72                                        Mensalmente
78                                        Mensalmente
79                                        Mensalmente
81                                        Mensalmente
82                                        Mensalmente
90                                        Mensalmente

Opção: Anualmente
    Respondente  \
9             8
14           12
21           18
60           53

   Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
9                                          Anualmente
14                                         Anualmente
21                                         Anualmente
60                                         Anualmente

Opção: Não Aplicável
    Respondente  \
2             2
3             3
7             7
10            9
11           10
22           19
29           25
30           26
35           31
36           32
39           35
43           38
56           49
59           52
68           60
86           77
89           79
93           83

   Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
2                                       Não Aplicável
3                                       Não Aplicável
7                                       Não Aplicável
10                                      Não Aplicável
11                                      Não Aplicável
22                                      Não Aplicável
29                                      Não Aplicável
30                                      Não Aplicável
35                                      Não Aplicável
36                                      Não Aplicável
39                                      Não Aplicável
43                                      Não Aplicável
56                                      Não Aplicável
59                                      Não Aplicável
68                                      Não Aplicável
86                                      Não Aplicável
89                                      Não Aplicável
93                                      Não Aplicável

In [15]:
with pd.ExcelWriter("respostas_individuais_agrupadas.xlsx") as writer:
    for i, (categoria, respostas_por_opcao) in enumerate(resultado.items()):
        frames = []
        for opcao, respostas in respostas_por_opcao.items():
            temp = respostas.copy()
            temp["Opção"] = opcao
            frames.append(temp)
        df_categoria = pd.concat(frames, ignore_index=True)
        nome_aba = f"{categoria[:27]}_{i}"  # garante unicidade e respeita limite de 31 chars
        df_categoria.to_excel(writer, sheet_name=nome_aba, index=False)

print("\nArquivo salvo: respostas_individuais_agrupadas.xlsx")

Arquivo salvo: respostas_individuais_agrupadas.xlsx

In [16]:
#files.download("respostas_individuais_agrupadas.xlsx")

## Criar a planilha

In [17]:
import re

# Definição das respostas diretas, indiretas, grandes e pequenas
resposta_direta = "Eu já trabalhei (ou trabalho) com segurança no processo de desenvolvimento de software."
resposta_indireta = "Meu grupo/equipe de desenvolvimento trabalha (ou trabalhou) com segurança, mas não estou diretamente envolvido em nenhuma tarefa."

resposta_pequena = ["Até 9 funcionários", "De 10 a 49 funcionários", "De 50 a 99 funcionários"]
resposta_grande = ["De 100 a 499 funcionários", "De 500 a 999 funcionários", "Mais de 1000 funcionários"]

resposta_especialistas = ['Penetration Tester', 'Security Engineer', 'Privacy Engineer', 'DevOps Engineer']
respostas_nao_especialistas_list = [
  'Developer (Backend, frontend, fullstack)',
  'Solution Architect',
  'Requirements Engineer',
  'Test Manager / Tester',
  'Product Owner',
  'Project Lead / Project Manager',
  'Data Scientist', 'UX/UI Designer',
]

# Nome das colunas corretas
coluna_experiencia = 'Você tem (ou teve) alguma experiência de trabalho relacionada à segurança de software no processo de desenvolvimento de software?'
coluna_tamanhoempresa = 'Qual o tamanho da empresa para a qual você trabalha atualmente?'
coluna_especialistas = 'Qual papel que melhor descreve suas atividades atuais em projetos de desenvolvimento de software?'
coluna_sistemas = 'Quais são os tipos de sistemas que você trabalha?'

# Filtra as respostas diretas e indiretas
diretas = df[df[coluna_experiencia] == resposta_direta].copy()
indiretas = df[df[coluna_experiencia] == resposta_indireta].copy()

# Filtra as respostas de empresas grandes e pequenas
grandes = df[df[coluna_tamanhoempresa].isin(resposta_grande)].copy()
pequenas = df[df[coluna_tamanhoempresa].isin(resposta_pequena)].copy()

# Helper function to check if a string contains any of the keywords
def contains_any_keyword(text, keywords):
    if pd.isna(text):
        return False
    text_lower = str(text).lower()
    for keyword in keywords:
        # Use regex with word boundaries to match whole words, case-insensitive
        if re.search(r'\b' + re.escape(keyword.lower()) + r'\b', text_lower):
            return True
    return False

# Filtra as respostas de especialistas
# Um respondente é considerado especialista se sua coluna 'coluna_especialistas'
# contém pelo menos uma das palavras-chave em 'resposta_especialistas'.
is_specialist_series = df[coluna_especialistas].apply(
    lambda x: contains_any_keyword(x, resposta_especialistas)
)
especialistas = df[is_specialist_series].copy()

# Filtra as respostas de não especialistas (aqueles que não são especialistas)
nao_especialistas = df[~is_specialist_series].copy()

In [18]:
print("Quantidade de participantes no grupo Experiência Direta:", len(diretas))
print("Quantidade de participantes no grupo Experiência Indireta:", len(indiretas))
print("--"*35)

print("Quantidade de participantes no grupo Big:", len(grandes))
print("Quantidade de participantes no grupo Small:", len(pequenas))
print("--"*35)

print("Quantidade de participantes no grupo Especialistas:", len(especialistas))
print("Quantidade de participantes no grupo Não Especialistas:", len(nao_especialistas))
print("--"*35)
print(f"Porcentagem de participantes no grupo Big: {len(grandes)/88:.1f}")
print(f"Porcentagem de participantes no grupo Small: {len(pequenas)/88:.1f}")

Quantidade de participantes no grupo Experiência Direta: 62
Quantidade de participantes no grupo Experiência Indireta: 21
----------------------------------------------------------------------
Quantidade de participantes no grupo Big: 65
Quantidade de participantes no grupo Small: 16
----------------------------------------------------------------------
Quantidade de participantes no grupo Especialistas: 62
Quantidade de participantes no grupo Não Especialistas: 21
----------------------------------------------------------------------
Porcentagem de participantes no grupo Big: 0.7
Porcentagem de participantes no grupo Small: 0.2

In [19]:
# Lista de colunas de preocupação
colunas_preocupacao = [
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Revisão de Código]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Modelagem de Ameaças]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Identificação de Casos de Abuso/Mau Uso]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Análise de Riscos Arquiteturais]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Testes de Penetração]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Gerenciamento de Riscos]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Gerenciamento de Vulnerabilidades]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Testes de Segurança Manuais/Automatizados]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Execução de Testes Fuzz]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Engenharia de Requisitos de Segurança]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Codificação Segura]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Resposta Emergencial ao Código]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Configurações e Gerenciamento de Segurança]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Monitoramento de Eventos de Segurança]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Auditorias de Segurança Externas]',
    'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Segurança da Cadeia de Suprimentos de Software]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Revisão de Código]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Modelagem de Ameaças]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Identificação de Casos de Abuso/Mau Uso]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Análise de Riscos Arquiteturais]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Testes de Penetração]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Gerenciamento de Riscos]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Gerenciamento de Vulnerabilidades]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Testes de Segurança Manuais/Automatizados]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Execução de Testes Fuzz]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Engenharia de Requisitos de Segurança]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Codificação Segura]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Resposta Emergencial ao Código]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Configurações e Gerenciamento de Segurança]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Monitoramento de Eventos de Segurança]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Auditorias de Segurança Externas]',
    'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Segurança da Cadeia de Suprimentos de Software]'
]

preocupacao_mapping = {
    #'Não Aplicável': 0,
    'Muito Baixo': 1,
    'Baixo': 2,
    'Moderado': 3,
    'Alto': 4,
    'Muito Alto': 5
}

In [20]:
# Lista para armazenar os resultados
!pip install cliffs-delta
from scipy import stats
from cliffs_delta import cliffs_delta

resultados = []

# Função que calcula as médias, p-value, effect size e retorna os resultados para um par de grupos
def calcular_dados(grupo1, grupo2, coluna):
    grupo1_filtrado = grupo1[grupo1[coluna] != "Não Aplicável"]
    grupo2_filtrado = grupo2[grupo2[coluna] != "Não Aplicável"]
    grupo1_mapeadas = grupo1[coluna].map(preocupacao_mapping)
    grupo2_mapeadas = grupo2[coluna].map(preocupacao_mapping)

    score_grupo1 = grupo1_mapeadas.mean()
    score_grupo2 = grupo2_mapeadas.mean()

    stat, p_value = stats.mannwhitneyu(grupo1_mapeadas.dropna(), grupo2_mapeadas.dropna(), alternative='greater')

    # cliffs delta
    effect_size = cliffs_delta(grupo1_mapeadas, grupo2_mapeadas)

    return score_grupo1, score_grupo2, p_value, effect_size

# Função que calcula a distribuição das respostas na escala Likert e a média ponderada para cada coluna
def calcular_likert_distribuicao(grupo, coluna):
    grupo_filtrado = grupo[grupo[coluna] != "Não Aplicável"]

    grupo_mapeadas = grupo_filtrado[coluna].map(preocupacao_mapping)
    total_respostas = grupo_mapeadas.value_counts().sort_index()
    media_ponderada = sum(total_respostas.index * (total_respostas / total_respostas.sum()))
    return total_respostas.to_dict(), media_ponderada

Collecting cliffs-delta
  Downloading cliffs_delta-1.0.0-py3-none-any.whl.metadata (1.7 kB)
Downloading cliffs_delta-1.0.0-py3-none-any.whl (10 kB)
Installing collected packages: cliffs-delta
Successfully installed cliffs-delta-1.0.0

[notice] A new release of pip is available: 24.1.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

ModuleNotFoundError: No module named 'scipy'

In [ ]:
# Loop que percorre cada coluna de preocupação, realiza as análises e armazena os resultados
for coluna in colunas_preocupacao:
    total_respostas, media_ponderada = calcular_likert_distribuicao(df, coluna)

    score_direto, score_indireto, p_value_direto_indireto, effect_size_direto_indireto = calcular_dados(diretas, indiretas, coluna)
    score_grande, score_pequena, p_value_grande_pequena, effect_size_grande_pequena = calcular_dados(grandes, pequenas, coluna)
    score_especialistas, score_nao_especialistas, p_value_especialistas_nao_especialistas, effect_size_especialistas_nao_especialistas = calcular_dados(especialistas, nao_especialistas, coluna)

    # Cria um dicionário com todos os resultados calculados e o adiciona à lista de resultados
    linha = {
        'Statement': coluna,
        'In total': total_respostas,
        'Overall score': media_ponderada,
        'Score Indirect': score_indireto,
        'Score Direct': score_direto,
        'P-value Indirect/Direct': p_value_direto_indireto,
        'Effect Size Indirect/Direct': effect_size_direto_indireto,
        'Score Big': score_grande,
        'Score Small': score_pequena,
        'P-value Big/Small': p_value_grande_pequena,
        'Effect Size Big/Small': effect_size_grande_pequena,
        'Score Specialist': score_especialistas,
        'Score Non-Specialist': score_nao_especialistas,
        'P-value Specialist/Non-Specialist': p_value_especialistas_nao_especialistas,
        'Effect Size Specialist/Non-Specialist': effect_size_especialistas_nao_especialistas,
    }
    resultados.append(linha)

In [ ]:
resultados

[{'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Revisão de Código]',
  'In total': {1: 2, 2: 9, 3: 26, 4: 17, 5: 18},
  'Overall score': 3.5555555555555554,
  'Score Indirect': np.float64(3.4),
  'Score Direct': np.float64(3.5964912280701755),
  'P-value Indirect/Direct': np.float64(0.37264630631684476),
  'Effect Size Indirect/Direct': (-0.22734254992319508, 'small'),
  'Score Big': np.float64(3.618181818181818),
  'Score Small': np.float64(3.533333333333333),
  'P-value Big/Small': np.float64(0.33502499443876116),
  'Effect Size Big/Small': (0.046153846153846156, 'negligible'),
  'Score Specialist': np.float64(3.482142857142857),
  'Score Non-Specialist': np.float64(3.8125),
  'P-value Specialist/Non-Specialist': np.float64(0.8312335438080605),
  'Effect Size Specialist/Non-Specialist': (-0.30721966205837176, 'small')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Modelagem de Ameaças]',
  'In total': {1: 2, 2: 13, 3: 24, 4: 16, 5: 8},
  'Overall score': 3.238095238095238,
  'Score Indirect': np.float64(3.0),
  'Score Direct': np.float64(3.2830188679245285),
  'P-value Indirect/Direct': np.float64(0.1806241396079169),
  'Effect Size Indirect/Direct': (-0.9370199692780338, 'large'),
  'Score Big': np.float64(3.2448979591836733),
  'Score Small': np.float64(3.230769230769231),
  'P-value Big/Small': np.float64(0.39692051001100326),
  'Effect Size Big/Small': (0.1605769230769231, 'small'),
  'Score Specialist': np.float64(3.3469387755102042),
  'Score Non-Specialist': np.float64(2.857142857142857),
  'P-value Specialist/Non-Specialist': np.float64(0.0735759128572656),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Identificação de Casos de Abuso/Mau Uso]',
  'In total': {1: 4, 2: 11, 3: 35, 4: 11, 5: 4},
  'Overall score': 3.0,
  'Score Indirect': np.float64(2.4545454545454546),
  'Score Direct': np.float64(3.111111111111111),
  'P-value Indirect/Direct': np.float64(0.020655589809348774),
  'Effect Size Indirect/Direct': (-0.9362519201228878, 'large'),
  'Score Big': np.float64(2.96),
  'Score Small': np.float64(3.142857142857143),
  'P-value Big/Small': np.float64(0.705593313416951),
  'Effect Size Big/Small': (-0.6634615384615384, 'large'),
  'Score Specialist': np.float64(3.12),
  'Score Non-Specialist': np.float64(2.6),
  'P-value Specialist/Non-Specialist': np.float64(0.034697819754608505),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Análise de Riscos Arquiteturais]',
  'In total': {1: 6, 2: 19, 3: 19, 4: 19, 5: 6},
  'Overall score': 3.0,
  'Score Indirect': np.float64(2.727272727272727),
  'Score Direct': np.float64(3.0517241379310347),
  'P-value Indirect/Direct': np.float64(0.1984848858042937),
  'Effect Size Indirect/Direct': (-0.9477726574500768, 'large'),
  'Score Big': np.float64(3.074074074074074),
  'Score Small': np.float64(2.7857142857142856),
  'P-value Big/Small': np.float64(0.17353150676805928),
  'Effect Size Big/Small': (-0.3769230769230769, 'medium'),
  'Score Specialist': np.float64(2.981818181818182),
  'Score Non-Specialist': np.float64(3.0714285714285716),
  'P-value Specialist/Non-Specialist': np.float64(0.6181791273830541),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Testes de Penetração]',
  'In total': {1: 7, 2: 14, 3: 21, 4: 12, 5: 14},
  'Overall score': 3.176470588235294,
  'Score Indirect': np.float64(3.1),
  'Score Direct': np.float64(3.189655172413793),
  'P-value Indirect/Direct': np.float64(0.4574813087110049),
  'Effect Size Indirect/Direct': (-0.946236559139785, 'large'),
  'Score Big': np.float64(3.1923076923076925),
  'Score Small': np.float64(3.142857142857143),
  'P-value Big/Small': np.float64(0.4456015311617267),
  'Effect Size Big/Small': (0.27884615384615385, 'small'),
  'Score Specialist': np.float64(3.2),
  'Score Non-Specialist': np.float64(3.076923076923077),
  'P-value Specialist/Non-Specialist': np.float64(0.37123172870380966),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Gerenciamento de Riscos]',
  'In total': {1: 4, 2: 11, 3: 29, 4: 15, 5: 6},
  'Overall score': 3.1230769230769235,
  'Score Indirect': np.float64(2.909090909090909),
  'Score Direct': np.float64(3.1666666666666665),
  'P-value Indirect/Direct': np.float64(0.29569219139760333),
  'Effect Size Indirect/Direct': (-0.9539170506912442, 'large'),
  'Score Big': np.float64(3.142857142857143),
  'Score Small': np.float64(3.2142857142857144),
  'P-value Big/Small': np.float64(0.5899747941498303),
  'Effect Size Big/Small': (0.2153846153846154, 'small'),
  'Score Specialist': np.float64(3.1320754716981134),
  'Score Non-Specialist': np.float64(3.0833333333333335),
  'P-value Specialist/Non-Specialist': np.float64(0.45371398573323757),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Gerenciamento de Vulnerabilidades]',
  'In total': {1: 2, 2: 7, 3: 31, 4: 14, 5: 16},
  'Overall score': 3.5,
  'Score Indirect': np.float64(3.5833333333333335),
  'Score Direct': np.float64(3.4827586206896552),
  'P-value Indirect/Direct': np.float64(0.6104287967573402),
  'Effect Size Indirect/Direct': (-0.8110599078341014, 'large'),
  'Score Big': np.float64(3.509433962264151),
  'Score Small': np.float64(3.533333333333333),
  'P-value Big/Small': np.float64(0.5155474577561279),
  'Effect Size Big/Small': (0.49423076923076925, 'large'),
  'Score Specialist': np.float64(3.4814814814814814),
  'Score Non-Specialist': np.float64(3.5625),
  'P-value Specialist/Non-Specialist': np.float64(0.5705090831312025),
  'Effect Size Specialist/Non-Specialist': (-0.9224270353302612, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Testes de Segurança Manuais/Automatizados]',
  'In total': {1: 4, 2: 11, 3: 21, 4: 21, 5: 13},
  'Overall score': 3.4,
  'Score Indirect': np.float64(3.5),
  'Score Direct': np.float64(3.3793103448275863),
  'P-value Indirect/Direct': np.float64(0.6445025770940875),
  'Effect Size Indirect/Direct': (-0.3425499231950845, 'medium'),
  'Score Big': np.float64(3.5185185185185186),
  'Score Small': np.float64(3.0),
  'P-value Big/Small': np.float64(0.06631735808845449),
  'Effect Size Big/Small': (0.175, 'small'),
  'Score Specialist': np.float64(3.4464285714285716),
  'Score Non-Specialist': np.float64(3.2142857142857144),
  'P-value Specialist/Non-Specialist': np.float64(0.25211245532896026),
  'Effect Size Specialist/Non-Specialist': (-0.18509984639016897, 'small')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Execução de Testes Fuzz]',
  'In total': {1: 3, 2: 13, 3: 19, 4: 12, 5: 8},
  'Overall score': 3.1636363636363636,
  'Score Indirect': np.float64(2.3333333333333335),
  'Score Direct': np.float64(3.2653061224489797),
  'P-value Indirect/Direct': np.float64(0.028627135030930277),
  'Effect Size Indirect/Direct': (-0.9155145929339478, 'large'),
  'Score Big': np.float64(3.25),
  'Score Small': np.float64(3.0),
  'P-value Big/Small': np.float64(0.1895748632131497),
  'Effect Size Big/Small': (0.2625, 'small'),
  'Score Specialist': np.float64(3.234042553191489),
  'Score Non-Specialist': np.float64(2.75),
  'P-value Specialist/Non-Specialist': np.float64(0.13560891683737708),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Engenharia de Requisitos de Segurança]',
  'In total': {1: 2, 2: 13, 3: 21, 4: 25, 5: 2},
  'Overall score': 3.1904761904761902,
  'Score Indirect': np.float64(2.8),
  'Score Direct': np.float64(3.2641509433962264),
  'P-value Indirect/Direct': np.float64(0.07578596068194351),
  'Effect Size Indirect/Direct': (-0.9331797235023042, 'large'),
  'Score Big': np.float64(3.276595744680851),
  'Score Small': np.float64(3.142857142857143),
  'P-value Big/Small': np.float64(0.3014665222542774),
  'Effect Size Big/Small': (0.15673076923076923, 'small'),
  'Score Specialist': np.float64(3.173076923076923),
  'Score Non-Specialist': np.float64(3.272727272727273),
  'P-value Specialist/Non-Specialist': np.float64(0.6841332744530313),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Codificação Segura]',
  'In total': {1: 1, 2: 17, 3: 18, 4: 19, 5: 10},
  'Overall score': 3.307692307692308,
  'Score Indirect': np.float64(2.9285714285714284),
  'Score Direct': np.float64(3.411764705882353),
  'P-value Indirect/Direct': np.float64(0.06216385160055331),
  'Effect Size Indirect/Direct': (-0.20276497695852536, 'small'),
  'Score Big': np.float64(3.36),
  'Score Small': np.float64(3.230769230769231),
  'P-value Big/Small': np.float64(0.39597339572159096),
  'Effect Size Big/Small': (-0.6682692307692307, 'large'),
  'Score Specialist': np.float64(3.2884615384615383),
  'Score Non-Specialist': np.float64(3.3846153846153846),
  'P-value Specialist/Non-Specialist': np.float64(0.5840610259743647),
  'Effect Size Specialist/Non-Specialist': (-0.43164362519201227, 'medium')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Resposta Emergencial ao Código]',
  'In total': {1: 4, 2: 13, 3: 22, 4: 9, 5: 7},
  'Overall score': 3.0363636363636366,
  'Score Indirect': np.float64(2.888888888888889),
  'Score Direct': np.float64(3.0652173913043477),
  'P-value Indirect/Direct': np.float64(0.40606632435083956),
  'Effect Size Indirect/Direct': (-0.9055299539170507, 'large'),
  'Score Big': np.float64(3.0952380952380953),
  'Score Small': np.float64(2.8461538461538463),
  'P-value Big/Small': np.float64(0.37027025331864083),
  'Effect Size Big/Small': (-0.7519230769230769, 'large'),
  'Score Specialist': np.float64(3.0217391304347827),
  'Score Non-Specialist': np.float64(3.111111111111111),
  'P-value Specialist/Non-Specialist': np.float64(0.5660682798765097),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Configurações e Gerenciamento de Segurança]',
  'In total': {1: 3, 2: 12, 3: 23, 4: 17, 5: 11},
  'Overall score': 3.318181818181818,
  'Score Indirect': np.float64(3.076923076923077),
  'Score Direct': np.float64(3.3773584905660377),
  'P-value Indirect/Direct': np.float64(0.1745822268591613),
  'Effect Size Indirect/Direct': (-0.4147465437788018, 'medium'),
  'Score Big': np.float64(3.411764705882353),
  'Score Small': np.float64(3.0),
  'P-value Big/Small': np.float64(0.10911633587681452),
  'Effect Size Big/Small': (-0.20192307692307693, 'small'),
  'Score Specialist': np.float64(3.3207547169811322),
  'Score Non-Specialist': np.float64(3.3076923076923075),
  'P-value Specialist/Non-Specialist': np.float64(0.48666340524745355),
  'Effect Size Specialist/Non-Specialist': (-0.4270353302611367, 'medium')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Monitoramento de Eventos de Segurança]',
  'In total': {1: 7, 2: 4, 3: 29, 4: 14, 5: 10},
  'Overall score': 3.25,
  'Score Indirect': np.float64(3.2857142857142856),
  'Score Direct': np.float64(3.24),
  'P-value Indirect/Direct': np.float64(0.5171505464736408),
  'Effect Size Indirect/Direct': (-0.9324116743471582, 'large'),
  'Score Big': np.float64(3.3333333333333335),
  'Score Small': np.float64(3.0),
  'P-value Big/Small': np.float64(0.27315236451053615),
  'Effect Size Big/Small': (-0.2519230769230769, 'small'),
  'Score Specialist': np.float64(3.2884615384615383),
  'Score Non-Specialist': np.float64(3.0833333333333335),
  'P-value Specialist/Non-Specialist': np.float64(0.33427441510397937),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Auditorias de Segurança Externas]',
  'In total': {1: 5, 2: 14, 3: 16, 4: 14, 5: 9},
  'Overall score': 3.137931034482759,
  'Score Indirect': np.float64(2.6666666666666665),
  'Score Direct': np.float64(3.2244897959183674),
  'P-value Indirect/Direct': np.float64(0.09089089967232311),
  'Effect Size Indirect/Direct': (-0.9185867895545314, 'large'),
  'Score Big': np.float64(3.1777777777777776),
  'Score Small': np.float64(3.0),
  'P-value Big/Small': np.float64(0.3475074753753823),
  'Effect Size Big/Small': (-0.40673076923076923, 'medium'),
  'Score Specialist': np.float64(3.0416666666666665),
  'Score Non-Specialist': np.float64(3.6),
  'P-value Specialist/Non-Specialist': np.float64(0.910422215528297),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avaliaria o nível de facilidade de uso das seguintes práticas de segurança de software? Considere marcar “Não Aplicável” para as práticas das quais você não utiliza.  [Segurança da Cadeia de Suprimentos de Software]',
  'In total': {1: 6, 2: 12, 3: 19, 4: 14, 5: 7},
  'Overall score': 3.0689655172413794,
  'Score Indirect': np.float64(3.375),
  'Score Direct': np.float64(3.02),
  'P-value Indirect/Direct': np.float64(0.7855416490168075),
  'Effect Size Indirect/Direct': (-0.9216589861751152, 'large'),
  'Score Big': np.float64(3.1777777777777776),
  'Score Small': np.float64(2.6666666666666665),
  'P-value Big/Small': np.float64(0.14251415838800385),
  'Effect Size Big/Small': (-0.6721153846153847, 'large'),
  'Score Specialist': np.float64(3.0638297872340425),
  'Score Non-Specialist': np.float64(3.090909090909091),
  'P-value Specialist/Non-Specialist': np.float64(0.5407502901463932),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Revisão de Código]',
  'In total': {2: 4, 3: 11, 4: 24, 5: 36},
  'Overall score': 4.226666666666667,
  'Score Indirect': np.float64(4.333333333333333),
  'Score Direct': np.float64(4.2),
  'P-value Indirect/Direct': np.float64(0.6690476158930665),
  'Effect Size Indirect/Direct': (-0.4731182795698925, 'medium'),
  'Score Big': np.float64(4.189655172413793),
  'Score Small': np.float64(4.333333333333333),
  'P-value Big/Small': np.float64(0.7830407366509105),
  'Effect Size Big/Small': (-0.8403846153846154, 'large'),
  'Score Specialist': np.float64(4.228070175438597),
  'Score Non-Specialist': np.float64(4.222222222222222),
  'P-value Specialist/Non-Specialist': np.float64(0.46789269507751735),
  'Effect Size Specialist/Non-Specialist': (-0.1259600614439324,
   'negligible')},
 {'Statement': 'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Modelagem de Ameaças]',
  'In total': {1: 1, 2: 3, 3: 11, 4: 21, 5: 29},
  'Overall score': 4.138461538461539,
  'Score Indirect': np.float64(3.9),
  'Score Direct': np.float64(4.181818181818182),
  'P-value Indirect/Direct': np.float64(0.21528103918920571),
  'Effect Size Indirect/Direct': (-0.9370199692780338, 'large'),
  'Score Big': np.float64(4.22),
  'Score Small': np.float64(3.857142857142857),
  'P-value Big/Small': np.float64(0.22200524164589713),
  'Effect Size Big/Small': (-0.2875, 'small'),
  'Score Specialist': np.float64(4.04),
  'Score Non-Specialist': np.float64(4.466666666666667),
  'P-value Specialist/Non-Specialist': np.float64(0.9620510564063108),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Identificação de Casos de Abuso/Mau Uso]',
  'In total': {1: 1, 2: 6, 3: 19, 4: 20, 5: 23},
  'Overall score': 3.8405797101449273,
  'Score Indirect': np.float64(3.9166666666666665),
  'Score Direct': np.float64(3.824561403508772),
  'P-value Indirect/Direct': np.float64(0.5915044232504775),
  'Effect Size Indirect/Direct': (-0.9485407066052227, 'large'),
  'Score Big': np.float64(3.888888888888889),
  'Score Small': np.float64(3.642857142857143),
  'P-value Big/Small': np.float64(0.32586563112871436),
  'Effect Size Big/Small': (-0.16538461538461538, 'small'),
  'Score Specialist': np.float64(3.814814814814815),
  'Score Non-Specialist': np.float64(3.933333333333333),
  'P-value Specialist/Non-Specialist': np.float64(0.6451094514804282),
  'Effect Size Specialist/Non-Specialist': (-1.0, 'large')},
 {'Statement': 'Com base em sua experiência, como você avalia a efetividade das seguintes práticas de segurança de software na prevenção, remoção ou detecção de problemas de segurança em seus projetos?  Considere marcar “Não Aplicável” para as práticas das quais você não utiliza. [Análise de Riscos Arquiteturais]',
  'In total': {1: 1, 2: 2, 3: 12, 4: 24, 5: 32},
  'Overall score': 4.183098591549296,
  'Score Indirect': np.float64(4.384615384615385),
  'Score Direct': np.float64(4.137931034482759),
  'P-value Indirect/Direct': np.float64(0.7387103205093204),
  'Effect Size Indirect/Direct': (-0.9393241167434716, 'large'),
  'Score Big': np.float64(4.181818181818182),
  'Score Small': np.float64(4.2),

In [ ]:
nao_aplicavel_summary = []

for coluna in colunas_preocupacao:
    # Contar as ocorrências de 'Não Aplicável'
    nao_aplicavel_count = df[coluna].value_counts().get('Não Aplicável', 0)

    # Contar o total de respostas válidas (excluindo NaN para o cálculo da porcentagem do que foi respondido)
    total_respostas_validas = df[coluna].dropna().shape[0]

    if total_respostas_validas > 0:
        nao_aplicavel_percentage = (nao_aplicavel_count / total_respostas_validas) * 100
    else:
        nao_aplicavel_percentage = 0

    nao_aplicavel_summary.append({
        'Coluna': coluna,
        'Contagem Não Aplicável': nao_aplicavel_count,
        'Porcentagem Não Aplicável': round(nao_aplicavel_percentage, 2)
    })

df_nao_aplicavel_summary = pd.DataFrame(nao_aplicavel_summary)

print("DataFrame com o resumo de 'Não Aplicável' por coluna:")
display(df_nao_aplicavel_summary)

DataFrame com o resumo de 'Não Aplicável' por coluna:

,Coluna,Contagem Não Aplicável,Porcentagem Não Aplicável
0,"Com base em sua experiência, como você avaliar...",11,13.25
1,"Com base em sua experiência, como você avaliar...",20,24.10
2,"Com base em sua experiência, como você avaliar...",18,21.69
3,"Com base em sua experiência, como você avaliar...",14,16.87
4,"Com base em sua experiência, como você avaliar...",15,18.07
5,"Com base em sua experiência, como você avaliar...",18,21.69
6,"Com base em sua experiência, como você avaliar...",13,15.66
7,"Com base em sua experiência, como você avaliar...",13,15.66
8,"Com base em sua experiência, como você avaliar...",28,33.73
9,"Com base em sua experiência, como você avaliar...",20,24.10
10,"Com base em sua experiência, como você avaliar...",18,21.69
11,"Com base em sua experiência, como você avaliar...",28,33.73
12,"Com base em sua experiência, como você avaliar...",17,20.48
13,"Com base em sua experiência, como você avaliar...",19,22.89
14,"Com base em sua experiência, como você avaliar...",25,30.12
15,"Com base em sua experiência, como você avaliar...",25,30.12
16,"Com base em sua experiência, como você avalia ...",8,9.64
17,"Com base em sua experiência, como você avalia ...",18,21.69
18,"Com base em sua experiência, como você avalia ...",14,16.87
19,"Com base em sua experiência, como você avalia ...",12,14.46
20,"Com base em sua experiência, como você avalia ...",14,16.87
21,"Com base em sua experiência, como você avalia ...",14,16.87
22,"Com base em sua experiência, como você avalia ...",10,12.05
23,"Com base em sua experiência, como você avalia ...",10,12.05
24,"Com base em sua experiência, como você avalia ...",24,28.92
25,"Com base em sua experiência, como você avalia ...",14,16.87
26,"Com base em sua experiência, como você avalia ...",17,20.48
27,"Com base em sua experiência, como você avalia ...",25,30.12
28,"Com base em sua experiência, como você avalia ...",17,20.48
29,"Com base em sua experiência, como você avalia ...",16,19.28
30,"Com base em sua experiência, como você avalia ...",22,26.51
31,"Com base em sua experiência, como você avalia ...",22,26.51

In [ ]:
# Identificar colunas de 'facilidade' e 'efetividade'
colunas_facilidade = [col for col in df_nao_aplicavel_summary['Coluna'] if 'facilidade de uso' in col.lower()]
colunas_efetividade = [col for col in df_nao_aplicavel_summary['Coluna'] if 'efetividade das seguintes práticas' in col.lower()]

# Filtrar o DataFrame de resumo para obter as porcentagens
df_facilidade = df_nao_aplicavel_summary[df_nao_aplicavel_summary['Coluna'].isin(colunas_facilidade)]
df_efetividade = df_nao_aplicavel_summary[df_nao_aplicavel_summary['Coluna'].isin(colunas_efetividade)]

# Calcular a média das porcentagens para cada grupo
media_facilidade = df_facilidade['Porcentagem Não Aplicável'].mean()
media_efetividade = df_efetividade['Porcentagem Não Aplicável'].mean()

# Criar um novo DataFrame com os resultados
df_resumo_aplicavel = pd.DataFrame({
    'Atributo': ['Facilidade de Uso', 'Efetividade'],
    'Média Porcentagem Não Aplicável': [round(media_facilidade, 2), round(media_efetividade, 2)]
})

print("DataFrame com o resumo da média de 'Não Aplicável' por atributo:")
display(df_resumo_aplicavel)

DataFrame com o resumo da média de 'Não Aplicável' por atributo:

            Atributo  Média Porcentagem Não Aplicável
0  Facilidade de Uso                            22.74
1        Efetividade                            19.35

In [ ]:
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
import pandas as pd
import os

# Caminho para salvar o arquivo temporário na pasta 'temp'
temp_dir = 'temp'
if not os.path.exists(temp_dir):
    os.makedirs(temp_dir)
temp_file_path = os.path.join(temp_dir, 'analise_temp.xlsx')

# Carregar o CSV e salvar como arquivo Excel temporário na pasta 'temp'
# df = pd.read_csv('C:/Users/Samsung/OneDrive/Documentos/AISE LAB/TCC_Aryely/Analise_Q1/resultados/analise.csv')
df = pd.DataFrame(resultados)

df.to_excel(temp_file_path, index=False)

# Carregar o arquivo Excel temporário
wb = openpyxl.load_workbook(temp_file_path)
ws = wb.active

# 1. Formatar Cabeçalhos
header_font = Font(bold=True)
header_fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")
header_alignment = Alignment(horizontal="center", vertical="center")
p_value_color = '4EF547'

for cell in ws[1]:  # Linha 1 são os cabeçalhos
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = header_alignment

# 2. Ajustar Largura das Colunas
for col in ws.columns:
    max_length = 0
    column = col[0].column_letter  # Pegue o nome da coluna
    for cell in col:
        try:
            if len(str(cell.value)) > max_length:
                max_length = len(str(cell.value))
        except:
            pass
    adjusted_width = (max_length + 2)
    ws.column_dimensions[column].width = adjusted_width

# 3. Formatar as Células com Números
for row in ws.iter_rows(min_row=2, min_col=2, max_col=ws.max_column):
    for cell in row:
        if isinstance(cell.value, (int, float)):  # Se o valor for numérico
            cell.alignment = Alignment(horizontal="center")
            cell.number_format = '0.00'  # Formato com 2 casas decimais


# 4. Formatação Condicional para P-values
for row in ws.iter_rows(min_row=2, min_col=6, max_col=6):  # Coluna P-value Indirect vs Direct
    for cell in row:
        v = float(cell.value)
        if v < 0.05:
            cell.fill = PatternFill(start_color=p_value_color, end_color=p_value_color, fill_type="solid")

for row in ws.iter_rows(min_row=2, min_col=10, max_col=10):  # Coluna P-value Big vs Small
    for cell in row:
        v = float(cell.value)
        if cell.value < 0.05:
            cell.fill = PatternFill(start_color=p_value_color, end_color=p_value_color, fill_type="solid")

for row in ws.iter_rows(min_row=2, min_col=14, max_col=14):  # Coluna P-value Specialist vs Non-Specialist
    for cell in row:
        v = float(cell.value)
        if cell.value < 0.05:
            cell.fill = PatternFill(start_color=p_value_color, end_color=p_value_color, fill_type="solid")


# Aplicando gradientes no Effect Size
for i, row in enumerate(df.itertuples(), start=2):
    pvalue_indirect_direct = row[6]
    pvalue_big_small = row[10]
    pvalue_specialist_non_specialist = row[14]

    # Get the numerical part of the effect size directly from the DataFrame row
    effect_size_ind_dir_value = row[7][0]
    effect_size_big_small_value = row[11][0]
    effect_size_spec_non_spec_value = row[15][0]

    cell_effect_size_ind_dir = ws.cell(row=i, column=7)
    cell_effect_size_big_small = ws.cell(row=i, column=11)
    cell_effect_size_spec_non_spec = ws.cell(row=i, column=15)

    # Definindo limites para o gradiente
    max_gray = 108  # Cinza mais escuro (cerca de #303030)
    min_gray = 230  # Cinza mais claro (cerca de #E6E6E6)

    # P-value Indirect vs Direct
    if pvalue_indirect_direct < 0.05:
        max_value_abs = df.loc[df["P-value Indirect/Direct"] < 0.05, "Effect Size Indirect/Direct"].apply(lambda x: abs(x[0])).max()
        if max_value_abs > 0:
            normalized_value = abs(effect_size_ind_dir_value) / max_value_abs
        else:
            normalized_value = 0
        gray_value = int(min_gray + (max_gray - min_gray) * normalized_value)
        fill_color = f"{gray_value:02X}{gray_value:02X}{gray_value:02X}"  # Formato hexadecimal RRGGBB
        cell_effect_size_ind_dir.fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")

    # P-value Big vs Small
    if pvalue_big_small < 0.05:
        max_value_abs = df.loc[df["P-value Big/Small"] < 0.05, "Effect Size Big/Small"].apply(lambda x: abs(x[0])).max()
        if max_value_abs > 0:
            normalized_value = abs(effect_size_big_small_value) / max_value_abs
        else:
            normalized_value = 0
        gray_value = int(min_gray + (max_gray - min_gray) * normalized_value)
        fill_color = f"{gray_value:02X}{gray_value:02X}{gray_value:02X}"  # Formato hexadecimal RRGGBB
        cell_effect_size_big_small.fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")

    # P-value Specialist vs Non-Specialist
    if pvalue_specialist_non_specialist < 0.05:
        max_value_abs = df.loc[df["P-value Specialist/Non-Specialist"] < 0.05, "Effect Size Specialist/Non-Specialist"].apply(lambda x: abs(x[0])).max()
        if max_value_abs > 0:
            normalized_value = abs(effect_size_spec_non_spec_value) / max_value_abs
        else:
            normalized_value = 0
        gray_value = int(min_gray + (max_gray - min_gray) * normalized_value)
        fill_color = f"{gray_value:02X}{gray_value:02X}{gray_value:02X}"  # Formato hexadecimal RRGGBB
        cell_effect_size_spec_non_spec.fill = PatternFill(start_color=fill_color, end_color=fill_color, fill_type="solid")

# 5. Aplicar Bordas
thin_border = Border(left=Side(style='thin'),
                     right=Side(style='thin'),
                     top=Side(style='thin'),
                     bottom=Side(style='thin'))

for row in ws.iter_rows():
    for cell in row:
        cell.border = thin_border

# 6. Congelar a Primeira Linha
ws.freeze_panes = "A2"

# Caminho para salvar o arquivo Excel formatado na pasta 'resultados_excel'
output_dir = 'resultados_excel'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
output_file_path = os.path.join(output_dir, 'analise_formatado_manw_clif.xlsx')
wb.save(output_file_path)

print(f"Arquivo temporário salvo em '{temp_file_path}'")
print(f"Formatação concluída e arquivo salvo como '{output_file_path}'.")

Arquivo temporário salvo em 'temp/analise_temp.xlsx'
Formatação concluída e arquivo salvo como 'resultados_excel/analise_formatado_manw_clif.xlsx'.